[package]
name = "examples"
version = "0.1.0"
authors = ["Chris Ohk <utilforever@gmail.com>"]
edition = "2018"

[dependencies.rustycity]
path = "../build/rustycity"

[[bin]]
name = "rustycity_console"
path = "rustycity_console.rs" 